name: End-to-end tests
on:
  push:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
  pull_request:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Test e2e
        run: yarn test:hl
