name: Cypress - End to end tests

on:
  push:
    branches:
      - main
      - develop
      - release-**
      - VSF2-304
  pull_request:
    branches:
      - main
      - develop
      - release-**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_tests:
    name: Cypress - End to end tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          php: [ "8.0" ]
          symfony: [ "^5.2" ]
          sylius: [ "~1.11.0" ]
          node: [ "14.19" ]
          mysql: [ "8.0" ]

    env:
      SYLIUS_API_ENDPOINT: http://localhost:8000/api/v2/graphql
      PORT: 3000
      MIDDLEWARE_URL: http://localhost:3000/api/
      SYLIUS_CHANNEL_CODE: FASHION_WEB
      SYLIUS_THUMBNAIL_ENDPOINT: http://localhost:8000/media/cache/sylius_shop_product_thumbnail
      SYLIUS_REGULAR_IMAGE_ENDPOINT: http://localhost:8000/media/cache/sylius_shop_product_large_thumbnail
      SYLIUS_PAYMENT_GATEWAY_HOST: http://localhost:8000/
      SYLIUS_DEFAULT_LOCALE: en_US
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout api code
        uses: actions/checkout@v2
        with:
          repository: BitBagCommerce/SyliusVueStorefront2Plugin
          path: SyliusVueStorefront2Plugin

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: "${{ matrix.php }}"
              extensions: intl
              tools: symfony
              coverage: none

      -   name: Setup Node
          uses: actions/setup-node@v1
          with:
              node-version: "${{ matrix.node }}"

      -   name: Shutdown default MySQL
          run: sudo service mysql stop

      -   name: Setup MySQL
          uses: mirromutth/mysql-action@v1.1
          with:
              mysql version: "${{ matrix.mysql }}"
              mysql root password: "root"

      -   name: Output PHP version for Symfony CLI
          run: php -v | head -n 1 | awk '{ print $2 }' > .php-version

      -   name: Install certificates
          run: symfony server:ca:install

      -   name: Run Chrome Headless
          run: google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &

      -   name: Run webserver
          run: (cd SyliusVueStorefront2Plugin/tests/Application && symfony server:start --port=8080 --dir=public --daemon)

      -   name: Get Composer cache directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      -   name: Cache Composer
          uses: actions/cache@v2
          with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
              restore-keys: |
                  ${{ runner.os }}-php-${{ matrix.php }}-composer-

      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.21.3'

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          config-file: packages/theme/tests/e2e/cypress-github-action.config.js
          install: yarn install
          build: yarn build
          start: yarn start
          browser: electron
          wait-on: 'http://localhost:3000'
