name: End-to-end tests
on:
  push:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
  pull_request:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SYLIUS_API_ENDPOINT: https://vsf2-demo-sylius.bitbag.io/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Test e2e
        run: yarn test:hl
