name: End-to-end tests
on:
  push:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
  pull_request:
    branches:
      - main
      - develop
      - release-**
      - VSF2-226
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      SYLIUS_API_ENDPOINT: ${{ secrets.SYLIUS_HOST_AUTHORIZED }}api/v2/graphql
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Run website
        run: yarn start

      - name: Run tests
        run: yarn test:hl
