name: Cypress - End to end tests

on:
  push:
    branches:
      - main
      - develop
      - release-**
  pull_request:
    branches:
      - main
      - develop
      - release-**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_tests:
    name: Cypress - End to end tests
    runs-on: ubuntu-22.04
    env:
      SYLIUS_API_ENDPOINT: http://localhost:8000/api/v2/graphql
      PORT: 3000
      MIDDLEWARE_URL: http://localhost:3000/api/
      SYLIUS_CHANNEL_CODE: FASHION_WEB
      SYLIUS_THUMBNAIL_ENDPOINT: http://localhost:8000/media/cache/sylius_shop_product_thumbnail
      SYLIUS_REGULAR_IMAGE_ENDPOINT: http://localhost:8000/media/cache/sylius_shop_product_large_thumbnail
      SYLIUS_PAYMENT_GATEWAY_HOST: http://localhost:8000/
      SYLIUS_DEFAULT_LOCALE: en_US
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
          cache: 'yarn'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: packages/theme/tests/e2e/cypress-github-action.config.js
          install: yarn install
          build: yarn build
          start: yarn start
          browser: electron
          wait-on: 'http://localhost:3000'

      - name: Failed build Slack notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        env:
          SLACK_CHANNEL: ${{ secrets.FAILED_BUILD_SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':x:'
          SLACK_TITLE: Failed build on ${{ github.event.repository.name }} repository
          SLACK_USERNAME: ${{ secrets.FAILED_BUILD_SLACK_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.FAILED_BUILD_SLACK_WEBHOOK }}